version: '3.8'

services:
  app:
    image: frontend-app
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - NEXT_PUBLIC_API_URL=11111
    ports:
      - '3000:3000'