version: '3.8'

services:
  app:
    image: frontend-app
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - NEXT_PUBLIC_API_URL=suka
    ports:
      - '3000:3000'